SyntaxError: invalid syntax (1401877282.py, line 1)

Step 1: Importing the libraries

In [67]:
import numpy as np
import pandas as pd

Importing dataset

In [68]:
datasets = pd.read_csv('data/Data.csv')
datasets

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

Handling the missing value

In [69]:
datasets.isnull().sum()

Country      0
Age          1
Salary       1
Purchased    0
dtype: int64

In [70]:
# Fill missing values in a column with the mean
datasets['Age'].fillna(datasets['Age'].mean(), inplace=True)

# Fill missing values in a column with a constant value
datasets['Age'].fillna(0, inplace=True)

datasets['Salary'].fillna(datasets['Salary'].mean(), inplace=True)

# Fill missing values in a column with a constant value
datasets['Salary'].fillna(0, inplace=True)

In [71]:
datasets.isnull().sum()

Country      0
Age          0
Salary       0
Purchased    0
dtype: int64

In [72]:
X = datasets.drop('Purchased', axis=1)
Y = datasets['Purchased']

Encoding categorical data

In [73]:
Y,Purchased = pd.factorize(datasets['Purchased'],sort=True)
print(Y)
print(Purchased)

[0 1 0 0 1 1 0 1 0 1]
Index(['No', 'Yes'], dtype='object')


Creating a dummy variable

In [74]:
onehotencoder = OneHotEncoder()
X = onehotencoder.fit_transform(X).toarray().astype('int')
labelencoder_Y = LabelEncoder()
Y =  labelencoder_Y.fit_transform(Y)

In [75]:
pd.DataFrame(X)

0   1   2   3   4   5   6   7   8   9   ...  13  14  15  16  17  18  19  \
0   1   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   
1   0   0   1   1   0   0   0   0   0   0  ...   1   0   0   0   0   0   0   
2   0   1   0   0   1   0   0   0   0   0  ...   0   0   1   0   0   0   0   
3   0   0   1   0   0   0   0   1   0   0  ...   0   0   0   0   1   0   0   
4   0   1   0   0   0   0   0   0   0   1  ...   0   0   0   0   0   1   0   
5   1   0   0   0   0   1   0   0   0   0  ...   0   0   0   1   0   0   0   
6   0   0   1   0   0   0   0   0   1   0  ...   0   1   0   0   0   0   0   
7   1   0   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   
8   0   1   0   0   0   0   0   0   0   0  ...   0   0   0   0   0   0   0   
9   1   0   0   0   0   0   1   0   0   0  ...   0   0   0   0   0   0   1   

   20  21  22  
0   1   0   0  
1   0   0   0  
2   0   0   0  
3   0   0   0  
4   0   0   0  
5   0   0   0  
6   0   0   0  
7   0   1   0  
8   0   0   1  
9   0   0   0  

[10 rows x 23 columns]

In [76]:
Y = pd.get_dummies(Y).to_numpy()



In [77]:
Y

array([[1, 0],
       [0, 1],
       [1, 0],
       [1, 0],
       [0, 1],
       [0, 1],
       [1, 0],
       [0, 1],
       [1, 0],
       [0, 1]], dtype=uint8)

Splitting the datasets into training sets and Test sets

In [80]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split( X , Y , test_size = 0.2, random_state = 0)

 Feature Scaling

In [84]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()

X = sc.fit_transform(X)
X_train_sc = sc.transform(X_train)
X_test_sc = sc.transform(X_test)

In [85]:
print(X_train)
X_train.shape

[[0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0]
 [1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0]
 [0 0 1 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0]
 [1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0]]


(8, 23)

งงทำเพื่ออะไร